* EmergingJetAnalysis
Main repository for Emerging Jet analysis
** Sub-packages
- EmJetAnalyzer: Main analyzer - analyzes input jets and outputs flat NTuple
- JetFilter: Applies basic kinematic selection for the signal region and outputs selected jets for analysis
- WJetFilter: Applies W+jet selection and outputs selected jets for analysis
** Dependencies
*** Cog - http://nedbatchelder.com/code/cog/index.html
Cog is used for code generation of classes with repetitive structure, e.g. ~EmergingJetAnalyzer/interface/OutputTree.h~
To install, simply execute:
#+BEGIN_SRC
pip install --user cogapp
#+END_SRC
** Quick instructions
*** To checkout latest code
#+BEGIN_SRC
cmsrel CMSSW_8_0_26_patch1
cd CMSSW_8_0_26_patch1/src
cmsenv
git cms-merge-topic yhshin11:fix-GetTrackTrajInfo # Needed for track trajectory info.
git clone https://github.com/yhshin11/EmergingJetAnalysis.git
#+END_SRC
*** To setup environment and compile
#+BEGIN_SRC
cmsenv
cd EmergingJetAnalysis
./buildAll.sh
#+END_SRC
*** To run main example config file
#+BEGIN_SRC
cmsRun Configuration/test/test_cfg.py
#+END_SRC
** General steps
For our analysis involving Emerging Jets, we follow the following steps:
1. Skim the data for useful events and select jets (JetFilter/WJetFilter)
2. Run the analyzer over the selected events/jets and produce ROOT files containing simple TTree objects (EmJetAnalyzer)
3. Make histograms/plots from the flat ROOT files
** Example config file
An example config file is provided at ~Configuration/test/test_cfg.py~. Make a copy of this file and edit ~process.source~ to run over an appropriate EDM file (AOD/AODSIM). You can now run the config file using cmsRun.

The config file comes with some command line options (defined at the top of the file):
- ~data~ (default: ~0~) - Must be set to 1 when running over real data and not MC.
- ~steps~ (default: ~skim,analyze~) - Determines which of the provided steps to execute. Setting ~skim~ turns on the basic selection step. Setting ~analyze~ turns on the analyzer.
- ~sample~ (default: ~signal~) - This sets the module parameters to be appropriate for different samples, e.g. if ~sample=wjet~ is set, the W+jet kinematic selection (WJetFilter) is used instead of the signal region kinematic selection (JetFilter). The details of the configuration are defined in ~Configuration/python/emJetTools.py~. (Warning: The logic here may change while the analysis is ongoing.)

For example to run both the skim and analyze steps over signal MC, simply do:
#+BEGIN_SRC
cmsRun Configuration/test/test_cfg.py data=0 steps=skim,analyze sample=signal
#+END_SRC
Since the provided options are exactly the default, you could also simply do:
#+BEGIN_SRC
cmsRun Configuration/test/test_cfg.py
#+END_SRC

Sometimes you may want to run the two steps separately. For instance since the skimming step is more stable while the analyze step is more in flux, you may want to run only the skimming step over a large dataset, so that you can run different versions of the analyze step later on. To run only the skimming step over data events, you can do:
#+BEGIN_SRC
cmsRun Configuration/test/test_cfg.py data=1 steps=skim
#+END_SRC

Note: By default, EmJetAnalyzer expects as input, jets that were selected by WJetFilter or JetFilter. This means that you cannot only run the analyze step over a bare AOD/AODSIM file.


